name: Bun - run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: "Bun - run tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies and run tests
        run: bun install

      - name: Get version
        run: bun run prebuild

      - name: Run tests
        run: bun run test
