name: Check CLI code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "cli/**"

jobs:
  checks:
    name: "Check CLI code - Bun"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - working-directory: cli
        run: bun install
      - working-directory: cli
        run: bun run test
      - working-directory: cli
        run: bun run lint
      - working-directory: cli
        run: bun run format
