name: Bun - run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: "Bun - run tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - working-directory: cli
        run: bun install
      - working-directory: cli
        run: bun run prebuild
      - working-directory: cli
        run: bun run test
